"""remover campo phone_number do model person

Revision ID: 09101af145b7
Revises: 3dc20289474f
Create Date: 2025-03-27 17:20:13.840153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09101af145b7'
down_revision = '3dc20289474f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index('ix_person_phone_number')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=50), nullable=False))
        batch_op.create_index('ix_person_phone_number', ['phone_number'], unique=False)

    # ### end Alembic commands ###
