"""Adicionar campos grade_test_1 e grade_test_2 ao modelo Person

Revision ID: 29b0dc6e4b77
Revises: eb7f60b515b8
Create Date: 2025-03-05 16:48:13.226283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b0dc6e4b77'
down_revision = 'eb7f60b515b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_test_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grade_test_2', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('grade_test_2')
        batch_op.drop_column('grade_test_1')

    # ### end Alembic commands ###
