"""ADDED AQ21 UNTIL AQ30

Revision ID: 2d71410ea8d0
Revises: 9b7d544e10a5
Create Date: 2025-04-25 16:40:32.134376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d71410ea8d0'
down_revision = '9b7d544e10a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AQ21', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('AQ22', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('AQ23', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('AQ24', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('AQ25', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('AQ26', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('AQ27', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('AQ28', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('AQ29', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('AQ30', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('AQ30')
        batch_op.drop_column('AQ29')
        batch_op.drop_column('AQ28')
        batch_op.drop_column('AQ27')
        batch_op.drop_column('AQ26')
        batch_op.drop_column('AQ25')
        batch_op.drop_column('AQ24')
        batch_op.drop_column('AQ23')
        batch_op.drop_column('AQ22')
        batch_op.drop_column('AQ21')

    # ### end Alembic commands ###
