"""Adicionar campo feedback_g e feedback_p ao modelo person

Revision ID: 3d81fede716b
Revises: 2b1fcb83d495
Create Date: 2025-03-27 16:49:20.719559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d81fede716b'
down_revision = '2b1fcb83d495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_g', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('feedback_p', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('feedback_p')
        batch_op.drop_column('feedback_g')

    # ### end Alembic commands ###
