"""remover campo feedback_g e feedback_p do model person

Revision ID: 3dc20289474f
Revises: 3d81fede716b
Create Date: 2025-03-27 17:18:07.729385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc20289474f'
down_revision = '3d81fede716b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.String(length=500), nullable=True))
        batch_op.drop_column('feedback_p')
        batch_op.drop_column('feedback_g')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_g', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('feedback_p', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
