"""Add education_level to Person model

Revision ID: 9b7d544e10a5
Revises: 5b3568043733
Create Date: 2025-04-25 11:20:51.012478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7d544e10a5'
down_revision = '5b3568043733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education_level', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('education_level')

    # ### end Alembic commands ###
