"""added column cpf

Revision ID: b887704ada2b
Revises: 2d71410ea8d0
Create Date: 2025-04-25 18:10:09.191172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b887704ada2b'
down_revision = '2d71410ea8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=False))
        batch_op.create_unique_constraint('[CPF]', ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
