"""Alterar coluna cpf para aceitar valores nulos

Revision ID: e205d6a370a2
Revises: b887704ada2b
Create Date: 2025-06-06 11:58:16.315861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e205d6a370a2'
down_revision = 'b887704ada2b'
branch_labels = None
depends_on = None


# CÓDIGO CORRIGIDO (COM BATCH MODE)
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
    # ### end Alembic commands ###
