"""Adicionar campos hobbies e work ao modelo Person

Revision ID: d10edffdfe1f
Revises: 29b0dc6e4b77
Create Date: 2025-03-10 21:21:17.862762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10edffdfe1f'
down_revision = '29b0dc6e4b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hobbies', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('work', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('work')
        batch_op.drop_column('hobbies')

    # ### end Alembic commands ###
