"""Adicionar campo age ao modelo Person

Revision ID: eb7f60b515b8
Revises: e9645ee67328
Create Date: 2025-03-05 15:52:34.380298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7f60b515b8'
down_revision = 'e9645ee67328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
